export enum Schemas {
  User = 'User',
  SystemConfig = 'SystemConfig',
  Team = 'Team',
  TeamMember = 'TeamMember',
  Post = 'Post',
  Comment = 'Comment',
  Reaction = 'Reaction',
  Task = 'Task',
  Project = 'Project',
  ProjectMember = 'ProjectMember',
  TeamRequest = 'TeamRequest',
  TeamRequestComment = 'TeamRequestComment',
  Email = 'Email',
  EmailLabel = 'EmailLabel',
  EmailConversation = 'EmailConversation',
}
